
# erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
# for offset=0. speed_to_erpm_gain = num_motor_poles*60/circumference_wheel_in_meters
speed_to_erpm_gain: 4614
speed_to_erpm_offset: 0.0

tachometer_ticks_to_meters_gain: 0.00225
# servo smoother - limits rotation speed and smooths anything above limit
max_servo_speed: 3.2 # radians/second
servo_smoother_rate: 75.0 # messages/sec

# servo smoother - limits acceleration and smooths anything above limit
max_acceleration: 20 # meters/second^2
throttle_smoother_rate: 75.0 # messages/sec

# servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
steering_angle_to_servo_gain: -0.9588
steering_angle_to_servo_offset: 0.52204
#steering_angle_to_servo_offset: 0.43

# publish odom to base link tf
vesc_to_odom/publish_tf: false

# car wheelbase is about 25cm 
wheelbase: .3175

vesc_driver:
  port: /dev/vesc1
  duty_cycle_min: -0.80
  duty_cycle_max: 0.80
  current_min: -60.0
  current_max: 60.0
  brake_min: -100000.0
  brake_max: 100000.0
  speed_min: -100000.0
  speed_max: 100000.0
  position_min: 0.0
  position_max: 0.0
  servo_min: 0.05
  servo_max: 0.95

vesc_driver2:
  port: /dev/vesc2
  duty_cycle_min: -0.80
  duty_cycle_max: 0.80
  current_min: -60.0
  current_max: 60.0
  brake_min: -100000.0
  brake_max: 100000.0
  speed_min: -100000.0
  speed_max: 100000.0
  position_min: 0.0
  position_max: 0.0
  servo_min: 0.05
  servo_max: 0.95

vesc_driver3:
  port: /dev/vesc3
  duty_cycle_min: -0.80
  duty_cycle_max: 0.80
  current_min: -60.0
  current_max: 60.0
  brake_min: -100000.0
  brake_max: 100000.0
  speed_min: -100000.0
  speed_max: 100000.0
  position_min: 0.0
  position_max: 0.0
  servo_min: 0.05
  servo_max: 0.95

vesc_driver4:
  port: /dev/vesc4
  duty_cycle_min: -0.80
  duty_cycle_max: 0.80
  current_min: -60.0
  current_max: 60.0
  brake_min: -100000.0
  brake_max: 100000.0
  speed_min: -100000.0
  speed_max: 100000.0
  position_min: 0.0
  position_max: 0.0
  servo_min: 0.05
  servo_max: 0.95